FROM rust:1.62.1-buster

# required by bingen
RUN apt-get update && \
	apt-get install -y \
		build-essential \
		cmake \
		clang \
		libclang-dev \
		llvm-dev \
		gcc-aarch64-linux-gnu \
		g++-aarch64-linux-gnu \
		libc6-dev-arm64-cross \
		git && \
	apt-get clean

#RUN rustup target add armv5te-unknown-linux-gnueabi
#RUN rustup target add arm-unknown-linux-gnueabihf
RUN rustup target add aarch64-unknown-linux-gnu
RUN rustup toolchain install stable-aarch64-unknown-linux-gnu

ENV CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc CXX_aarch64_unknown_linux_gnu=aarch64-linux-gnu-g++

RUN cargo install cargo-bitbake

RUN echo '[target.aarch64-unknown-linux-gnu]\n\
linker = "aarch64-linux-gnu-gcc"\n'\
>> /usr/local/cargo/config

RUN mkdir -p /tmp
RUN cd /tmp && git clone https://github.com/seife/opkg-utils.git && cd /tmp/opkg-utils && PREFIX=/usr make install

ENV LLVM_CONFIG_PATH=llvm-config
ENV PROJECT_PATH=/chirpstack-udp-forwarder
RUN mkdir -p $PROJECT_PATH
WORKDIR $PROJECT_PATH

COPY . /chirpstack-udp-forwarder
RUN cargo fetch
